//  @ts-check

import { tanstackConfig } from "@tanstack/eslint-config"

export default [
  ...tanstackConfig,
  {
    // vite.config.ts is excluded from tsconfig (vite-plus's config type exceeds
    // TS's instantiation depth limit), so the type-aware parser has no project
    // for it and errors out. Vite type-checks the file when it loads it.
    // routeTree.gen.ts is generated by TanStack Router.
    ignores: [
      "vite.config.ts",
      "routeTree.gen.ts",
      "src/routeTree.gen.ts",
      ".output/**",
      "dist/**",
    ],
  },
]
